from .learning_patterns import LEARNING_PATTERNS
from .topic_categories import TOPIC_CATEGORIES
from .filter_patterns import CONVERSATIONAL_PHRASES, GENERIC_TERMS, TECHNICAL_KEYWORDS
from .topic_categories_pre import PREREQUISITES